workflows:
  android-apk:
    name: Android APK (Flutter)
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.pumply.app"
    scripts:
      - |
        echo "Ensuring Flutter project structure..."
        if [ ! -d "android" ] || [ ! -d "ios" ]; then
          flutter create .
        fi
        flutter pub get
        flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - .pub-cache
        - build
  web-release:
    name: Web Release (Flutter)
    environment:
      flutter: stable
    scripts:
      - |
        if [ ! -f "pubspec.yaml" ]; then
          echo "pubspec.yaml missing"; exit 1;
        fi
        if [ ! -d "web" ]; then
          flutter create .
        fi
        flutter pub get
        flutter build web --release
    artifacts:
      - build/web/**